# Generated by Django 5.0.1 on 2024-02-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
