# Generated by Django 5.0.1 on 2024-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0004_articlepost_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="article/%Y%m%d/"),
        ),
    ]
